"""empty message

Revision ID: 2cc8936a45da
Revises: dfe0dbd149cb
Create Date: 2023-08-23 19:52:05.361512

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2cc8936a45da'
down_revision = 'dfe0dbd149cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usuário',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=45), nullable=False),
    sa.Column('email', sa.String(length=90), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usuário')
    # ### end Alembic commands ###
