"""empty message

Revision ID: 740c43d90df2
Revises: 2cc8936a45da
Create Date: 2023-08-25 20:50:08.434649

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '740c43d90df2'
down_revision = '2cc8936a45da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Conta', sa.Column('usuario_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Conta', 'usuário', ['usuario_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Conta', type_='foreignkey')
    op.drop_column('Conta', 'usuario_id')
    # ### end Alembic commands ###
